dist: trusty

language: node_js
node_js:
  - "7"

addons:
  mariadb: "10"
  sonarcloud:
    organization: "sterioss" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

services:
  - mariadb

before_install:
  - sudo chown -R travis .
  - npm install
  - npm install -g pm2
  - curl -OL https://github.com/loadimpact/k6/releases/download/v0.20.0/k6-v0.20.0-linux64.tar.gz
  - tar -xzf k6-v0.20.0-linux64.tar.gz
  - sudo cp k6-v0.20.0-linux64/k6 /usr/local/bin

script:
  - mysql -e 'CREATE DATABASE badgeuse; CREATE USER "uhaSQL"@"localhost" IDENTIFIED BY "uha";'
  - mysql -u root --password="" < ./BDD/init.d/1-BDD-Badgeuse-tables.sql
  - mysql -u root --password="" < ./BDD/init.d/2-BDD-Badgeuse-Data.sql
  - pm2 start index.js --name badgeuse
  - sleep "5"
  - pm2 show 0
  - pm2 logs badgeuse [--lines 1000]
  - curl 127.0.0.1:8080
  - npm test
  - npm run report-coverage
  - sonar-scanner

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: badgeuse-intelligente

after_deploy:
  - k6 run k6/main.js