dist: trusty

language: node_js
node_js:
  - "7"

services:
  - mysql

addons:
  sonarcloud:
    organization: "sterioss" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

before_install:
  - npm install
  - npm install -g pm2
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install dpkg
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
  - echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install k6

script:
  - mysql -e 'CREATE DATABASE badgeuse; CREATE USER "uhaSQL"@"localhost" IDENTIFIED BY "uha"; USE badgeuse; source ./BDD/init.d/1-BDD-Badgeuse-tables.sql;'
  - mysql -e 'source ./BDD/init.d/2-BDD-Badgeuse-Data.sql'
  - pm2 start index.js --name badgeuse
  - curl 127.0.0.1:8080
  - sleep "30"
  - npm test
  - npm run report-coverage
  - sonar-scanner

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: badgeuse-intelligente

after_deploy:
  - k6 run k6/main.js