dist: trusty

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  - git fetch --unshallow
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install dpkg
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
  - echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install k6

script:
  - docker-compose -f docker-compose.test.yml up -d
  - sleep "30"
  - docker exec -ti badgeuse-node npm test
  - docker exec -ti badgeuse-node npm run report-coverage
  - docker exec -ti badgeuse-node npm run sonar-scanner $SONAR_TOKEN

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: badgeuse-intelligente