version: '3.1'

services:
  badgeuse-node:
    container_name: badgeuse-node
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    env_file:
      - ./.env

  mariadb:
    image: library/mariadb:latest
    volumes:
      - ./BDD/data:/var/lib/mysql:z
      - ./BDD/init.d:/docker-entrypoint-initdb.d:z
    env_file:
      - ./.env
    expose:
      - 3306
