version: '3.1'

services:
  web:
    build:
      context: client
    ports:
      - 81:80
    depends_on:
      - node


  node:
    build:
      context: .
    environment:
      - PORT_ANGULAR=81
      - HOST_ANGULAR=10.3.1.152 #ipLocal adress
    ports:
      - 8080:8080
    depends_on:
      - mariadb

  mariadb:
    image: library/mariadb:latest
    volumes:
      - ./BDD/data:/var/lib/mysql
      - ./BDD:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_USER: "uhaSQL"
      MYSQL_PASSWORD: "uha"
      MYSQL_DATABASE: "badgeuse"
    expose:
      - 3306

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - '80'
