version: '3.1'

services:
  web:
    build:
      context: web
    volumes:
      - .:/var/www/html
    ports: 
      - 81:80
    depends_on:
      - node

  node:
    image: node:alpine
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: >
      sh -c "npm install && node index.js"

  mariadb:
    image: library/mariadb:latest
    volumes:
      - ./BDD/data:/var/lib/mysql
      - ./BDD:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_USER: "uhaSQL"
      MYSQL_PASSWORD: "uha"
      MYSQL_DATABASE: "badgeuse"
    expose:
      - 3306

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - '80'

