version: '3.1'

services:


  badgeuse-web-dev:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    command: npm run start-docker
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 4200:4200
    depends_on:
      - badgeuse-node-dev
    env_file:
      - ./.env


  badgeuse-node-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: ["nodemon", "index.js"]
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - mariadb
    env_file:
      - ./.env

  mariadb:
    image: library/mariadb:latest
    volumes:
      - ./BDD/data:/var/lib/mysql:z
      - ./BDD/init.d:/docker-entrypoint-initdb.d:z
    env_file:
      - ./.env
    expose:
      - 3306

  adminer:
    image: adminer
    restart: always
    ports:
      - ${PORT_ADMINER}:8080


